# This is a basic workflow to help you get started with Actions

name: autosync

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: install w3m
        run: sudo apt-get install w3m

      - name: pull repo
        run: git pull origin main
        
      - name: define page - clear
        run: page="$(w3m -dump https://www.google.com)"  

      - name: define page
        run: page="$(w3m -dump https://dlj.tf/i9o0Znl)"

      - name: write file
        run: sudo echo "$page" > ./nodelist

      - name: commit
        run: git commit -am "scheduled task - workflow"
        
      - name: push
        run: git push origin main
